### ISSUE TITLE
Hide DebugBar on @media print

### ISSUE THREAD

**Issue by fernandosavio** [barryvdh/laravel-debugbar#358]
I think DebugBar should be invisible when printing a page. It can be annoying when debugging a print style.

This code should do the job...

``` css
@media print {
  div.phpdebugbar {
    display: none;
  }
}
```

Thanks
